export const defaultState = {
  particleCount: 500,
  particleColor: '#1e90ff',
  particleShape: 'circle',
  particleGlow: 8,
  particleSpeed: 1,
  interactiveEffect: 'none',
  magnetEnabled: true,
  magnetStrength: 220,
  magnetFalloff: 1.6,
  magnetSize: 22,
  magnetColor: '#ff4500',
  showFieldLines: false,
  fieldLineColor: '#ffffff',
  lifeMode: false,
  lifeSpeed: 10,
  lifeCellSize: 16,
  lifeRule: 'B3/S23',
  lifeMagnetBias: 0.4,
  lifeAliveColor: '#1e90ff',
  lifeDeadColor: '#0b1020',
  screensaverEnabled: false,
  screensaverDrift: 14,
  screensaverInterval: 20,
};
